### GET request to /ping endpoint
GET http://localhost:5000/ping
###

### POST resquest to /auth/signup
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "email": "test3@testing.com",
  "password": "secret"
}

###